
package cn.dx.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ICreateInfoServiceService", targetNamespace = "http://ideal.sh.cn.tc", wsdlLocation = "http://10.145.204.133/IdealTC/ws/CreateInfoService?wsdl")
public class ICreateInfoServiceService
    extends Service
{

    private final static URL ICREATEINFOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ICREATEINFOSERVICESERVICE_EXCEPTION;
    private final static QName ICREATEINFOSERVICESERVICE_QNAME = new QName("http://ideal.sh.cn.tc", "ICreateInfoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.145.204.133/IdealTC/ws/CreateInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ICREATEINFOSERVICESERVICE_WSDL_LOCATION = url;
        ICREATEINFOSERVICESERVICE_EXCEPTION = e;
    }

    public ICreateInfoServiceService() {
        super(__getWsdlLocation(), ICREATEINFOSERVICESERVICE_QNAME);
    }

    public ICreateInfoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ICREATEINFOSERVICESERVICE_QNAME, features);
    }

    public ICreateInfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, ICREATEINFOSERVICESERVICE_QNAME);
    }

    public ICreateInfoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ICREATEINFOSERVICESERVICE_QNAME, features);
    }

    public ICreateInfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICreateInfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICreateInfoService
     */
    @WebEndpoint(name = "ICreateInfoServicePort")
    public ICreateInfoService getICreateInfoServicePort() {
        return super.getPort(new QName("http://ideal.sh.cn.tc", "ICreateInfoServicePort"), ICreateInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICreateInfoService
     */
    @WebEndpoint(name = "ICreateInfoServicePort")
    public ICreateInfoService getICreateInfoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ideal.sh.cn.tc", "ICreateInfoServicePort"), ICreateInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ICREATEINFOSERVICESERVICE_EXCEPTION!= null) {
            throw ICREATEINFOSERVICESERVICE_EXCEPTION;
        }
        return ICREATEINFOSERVICESERVICE_WSDL_LOCATION;
    }

}
